### PR TITLE
Migrate CI to actions, build artifacts

### PR DESCRIPTION
**Pull request by wussler**
- Use Actions instead of Travis
- Build for iOS, mac OS, and Android
- Make artifacts available

Co-authored by: @marinthiercelin

### CODE REVIEW

**Comment by wussler** [comment]
I promise to squash when merging :sweat_smile:

**Comment by wussler** [comment]
And here are the test artifacts:
- https://github.com/wussler/gopenpgp/actions/runs/308806560
- https://github.com/wussler/gopenpgp/actions/runs/308806551

**Review by marinthiercelin — COMMENTED** [review]
In android.yml I think you checkout twice.
I am not sure the build.sh will work directly from inside the directory of gopenpgp

**Comment by wussler** [comment]
@marinthiercelin Yes, it works directly there, but I'm not 100% sure whether on the current (checked-out) version.

You're right, on android we check-out twice, I'll fix that

**Comment by marinthiercelin** [comment]
Can you put the Crypto.xcframework in the artifacts as well? it combines the frameworks for all appleplatforms
Btw, maybe we can modify the script to call it Gopenpgp.framework instead

**Comment by wussler** [comment]
@marinthiercelin I like the name gopenpgp too, renamed and added :+1:

**Review by marinthiercelin — COMMENTED** [review]
You also need to modify $BUILD_NAME in build.sh, otherwise it won't genereate with the right name

**Comment by marinthiercelin** [comment]
And why do you upload a Gopenpgp.framework instead of Gopenpgp.xcframework ?
I should be xcframework

**Review by marinthiercelin — COMMENTED** [review]
Why do you delete the remove_dir bash function ?
I use it in the build function. So in its current state, the script is goind to fail

**Comment by wussler** [comment]
Now everything works, just not renamed :)

**Comment by wussler** [comment]
It's now renamed and ready for merge :)

**Review by marinthiercelin — APPROVED** [review]

**Pull request merged**
